### ISSUE TITLE
Compatibility with GHC 9.2

### ISSUE THREAD

**Issue by sjakobi** [lspitzner/czipwith#4]
This package already builds with `--allow-newer`, so it might be sufficient to bump the bounds on `base` and `template-haskell`.

**Comment by LennartSpitzner** [comment]
I started looking into this, but unfortunately my SSD died while preparing/building the nix-shell for `ghc-9.2`. I have backups, but it'll take me a few more days to get my dev machine back up and running.

**Comment by lspitzner** [comment]
Yep, all green with relaxed bounds. Released new x-revision "1.0.1.4-x1" to hackage.

**Comment by sjakobi** [comment]
Thank you! :)
